### ISSUE TITLE
[avni-client] UI broken for multiple programs for member under HH profile

### ISSUE THREAD

**Issue by nupoorkhandelwal** [avniproject/avni-client#961]
Support ticket - https://avni.freshdesk.com/a/tickets/2632

UI is broken when individual is enrolled in multiple programs (On the HH profile view)![Screenshot_4_Avni - Ajit Mangrule.jpg](https://images.zenhubusercontent.com/5d1469c9b0b5db61870d0f5c/df4fe067-e890-4b96-93e3-b1d481d32bf0)

**Comment by 1t5j0y** [comment]
![Screenshot_1685512578.png](https://images.zenhubusercontent.com/5d8a51c647755200010d2fda/90e83064-ba16-4d17-be7c-97bd8f7fe293)

**Comment by AchalaBelokar** [comment]
- [ ]S is cutting in the actions label...
![Screenshot 2023-06-05 at 2.45.05 PM.png](https://images.zenhubusercontent.com/62722c06dedab50580ce62fa/21896880-8339-4337-bb76-e163d328cd3c) 

- [ ] Unavailable text is cutting
![Screenshot 2023-06-05 at 2.54.46 PM.png](https://images.zenhubusercontent.com/62722c06dedab50580ce62fa/62053011-4a10-4c13-8296-c4dd45edd57c)

**Comment by 1t5j0y** [comment]
fixed

**Comment by nupoorkhandelwal** [comment]
@vinayvenu this is still broken on 3.40.1

![Image](https://github.com/avniproject/avni-client/assets/37863085/62a1d352-4c63-439a-863a-6c2df0507d3a)

**Comment by vinayvenu** [comment]
@nupoorkhandelwal this is a 4.0.0 card.
